load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    urls = [
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
    ],
    sha256 = "1c531376ac7e5a180e0237938a2536de0c54d93f5c278634818e0efc952dd56c",
)
load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()

all_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])"""

http_archive(
    name = "rules_foreign_cc",
    sha256 = "d54742ffbdc6924f222d2179f0e10e911c5c659c4ae74158e9fe827aad862ac6",
    strip_prefix = "rules_foreign_cc-0.2.0",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.2.0.tar.gz",
)

load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")

# This sets up some common toolchains for building targets. For more details, please see
# https://github.com/bazelbuild/rules_foreign_cc/tree/main/docs#rules_foreign_cc_dependencies
rules_foreign_cc_dependencies()


# Now dependencies:

#new_local_repository(
#name = "external",
#    path = "external",
#    build_file = "external/BUILD",
#)

http_archive(
   name = "zmq",
   build_file_content = all_content,
   strip_prefix = "zeromq-4.3.2",
   urls = ["https://github.com/zeromq/libzmq/releases/download/v4.3.2/zeromq-4.3.2.tar.gz"],
)

http_archive(
   name = "zmqpp",
   build_file_content = all_content,
   strip_prefix = "zmqpp-4.2.0",
   urls = ["https://github.com/zeromq/zmqpp/archive/refs/tags/4.2.0.tar.gz"],
)

http_archive(
   name="spdlog",
   build_file_content = all_content,
   strip_prefix = "spdlog-1.8.5",
   url = "https://github.com/gabime/spdlog/archive/refs/tags/v1.8.5.tar.gz",
)

http_archive(
  name = "gtest",
  urls = ["https://github.com/google/googletest/archive/refs/tags/release-1.10.0.tar.gz"],
  strip_prefix = "googletest-release-1.10.0",
)
